import Head from "next/head";
import Image from "next/image";
import styles from "../styles/header.module.scss";
import NavHeader from "./navmain/NavHeader";
import { Children } from "react";
import CarosuelSlide from "./carosuel";
import { Box } from "@mantine/core";
import Itemspost from "./itemspost";

export default function Home({ children }) {
  return (
    <div className={styles.contain}>
      <Head>
        <title>NewPost</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.contain}>
        <NavHeader></NavHeader>
        {children}
        <Box
          sx={{
            maxWidth: "90vw",
            width: "100%",
            height: "60vh",
            background: "black",
            marginTop: "40px",
          }}
        >
          <CarosuelSlide></CarosuelSlide>
        </Box>
        <Box
          sx={{
            maxWidth: "90vw",
            width: "100%",
            height: "100vh",
            marginTop: "40px",
          }}
        >
          <Itemspost></Itemspost>
        </Box>
      </main>
    </div>
  );
}
