import Head from "next/head";
import React, { memo } from "react";
import styles from "../../styles/header.module.scss";
import NavHeader from "../navmain/NavHeader";
import InfoCompo from "./components/InfoCompo";

const index = () => {
  return (
    <div className={styles.contain}>
      <Head>
        <title>NewPost</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.contain}>
        <NavHeader></NavHeader>
        <InfoCompo></InfoCompo>
      </main>
    </div>
  );
};

export default memo(index);
